"""Add three-tier permission system

Revision ID: 5030dd6273fd
Revises: bde08dcf48ed
Create Date: 2025-10-07 21:34:51.081165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5030dd6273fd'
down_revision = 'bde08dcf48ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_league_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_owner', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_primary_owner', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_primary_owner')
    op.drop_column('users', 'is_owner')
    op.drop_column('users', 'is_league_admin')
    # ### end Alembic commands ###

